option(CMT_ENABLE_CCACHE                "Enable the integration of ccache into the build system"                ON)
option(CMT_ENABLE_CLANG_BUILD_ANALYZER  "Enable the integration of clang-tidy into the build system"            ON)
option(CMT_ENABLE_CLANG_FORMAT          "Enable the integration of clang-format into the build system"          ON)
option(CMT_ENABLE_CLANG_TIDY            "Enable the integration of clang-tidy into the build system"            ON)
option(CMT_ENABLE_CODECHECKER           "Enable the integration of codechecker into the build system"           OFF)
option(CMT_ENABLE_COTIRE                "Enable the integration of cotire into the build system"                ON)
option(CMT_ENABLE_COVERAGE              "Enable the integration of coverage into the build system"              ON)
option(CMT_ENABLE_CPPCHECK              "Enable the integration of cppcheck into the build system"              ON)
option(CMT_ENABLE_CPPLINT               "Enable the integration of cppcheck into the build system"              ON)
option(CMT_ENABLE_DEPENDENCY_GRAPH      "Enable the integration of dependency-graphs into the build system"     ON)
option(CMT_ENABLE_IWYU                  "Enable the integration of include-what-you-use into the build system"  ON)
option(CMT_ENABLE_LIZARD                "Enable the integration of lizard into the build system"                ON)
option(CMT_ENABLE_LTO                   "Enable the integration of lto into the build system"                   ON)
option(CMT_ENABLE_SANITIZERS            "Enable the integration of sanitizers into the build system"            ON)


option(CMT_ENABLE_COMPILER_OPTION_CHECKS    "Enable checks in compiler options"         ON)
option(CMT_ENABLE_LINKER_OPTION_CHECKS      "Enable checks in linker options"           ON)
option(CMT_ENABLE_PCH                       "Enable the usage of pre-compiled headers"  ON)
option(CMT_ENABLE_UNITY_BUILD               "Enable unity builds optimization"          ON)
